services:
  - type: web
    name: rbs-photo-album-api
    runtime: node
    plan: free
    region: singapore
    buildCommand: cd server && npm install
    startCommand: cd server && node index.js
    envVars:
      - key: NODE_VERSION
        value: "18"
      - key: PORT
        value: "10000"
      - key: ADMIN_PASSWORD
        sync: false
      - key: QINIU_ACCESS_KEY
        sync: false
      - key: QINIU_SECRET_KEY
        sync: false
      - key: QINIU_BUCKET
        sync: false
      - key: QINIU_DOMAIN
        sync: false
